### ISSUE TITLE
[Feature] Add Budget Tracker Calculator

### ISSUE THREAD

**Issue by Maheshwari-Love** [Rakesh9100/CalcDiverse#1532]
### Description

I want to add the new Cacl for the budget tracking 

### Screenshots

![image](https://github.com/Rakesh9100/CalcDiverse/assets/142833275/55877dbb-ff99-4057-aac3-3facd3ebd4a5)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Maheshwari-Love** [comment]
@Rakesh9100 please assign this  task ...

**Comment by jessicachawla** [comment]
@Rakesh9100 this issue can be assigned 
@Maheshwari-Love while coding make sure to keep the ui similar to the existing website

**Comment by Maheshwari-Love** [comment]
> @Rakesh9100 this issue can be assigned @Maheshwari-Love while coding make sure to keep the ui similar to the existing website

@Rakesh9100 please assign me

**Comment by Rakesh9100** [comment]
Go ahead @Maheshwari-Love
